### ISSUE TITLE
[BUG] 렌더링하지 않은 대사를 내보내기 시도할 경우 프로그램이 강제 종료됨

### ISSUE THREAD

**Issue by Aden1126** [EX3exp/MiriVoice#5]
**버그 설명**
프로그램 실행 이후 재생을 한번도 하지 않은 대사 (렌더링하지 않은 대사)를 내보내기 시도할 경우 프로그램이 강제 종료됨

**로그**
[log20241023.txt](https://github.com/user-attachments/files/17480456/log20241023.txt)

**데스크탑**
 - OS: Windows 10.0.19045 x64
 - Version: 1.1.1.0

**재현 과정**
1. mrp 파일 실행
2. 재생 버튼을 누르지 않은 대사를 '[내보내기] 선택된 대사를 오디오로 (.wav)'로 저장 시도
3. 파일명 입력 후 저장 버튼을 누르면 강제 종료됨

**추가 설명**
이 이슈와는 별개로, 로그를 보니 실질적인 사용에 지장을 주지는 않지만 다른 오류도 발생하는 것 같음

**Comment by EX3exp** [comment]
짚어 주신 부분들이 [v1.1.1.1](https://github.com/EX3exp/MiriVoice/releases/tag/1.1.1.1) 업데이트에서 해결되었습니다. 버그 제보 감사합니다!
